library(tidyverse)
library(tidytext)
library(gutenbergr)
library(dplyr)

load("../data/sales_scraped_information.RData")

punk_attributes <-data_frame(id = c(1:6674),
                             attributes = (punk_attributes))

punk_attributes$attributes<- gsub('[c()"]',"", punk_attributes$attributes)
as.data.frame(punk_attributes)


punk_attributes_test <- punk_attributes %>%
  group_by(id) %>% 
  mutate(Bandana = ifelse(grepl("Bandana", attributes), 1, 0),
         Beanie = ifelse(grepl("Beanie", attributes), 1, 0),
         Choker = ifelse(grepl("Choker", attributes), 1, 0),
         Pilot_Helmet = ifelse(grepl("Pilot Helmet", attributes), 1, 0),
         Tiara = ifelse(grepl("Tiara", attributes), 1, 0),
         Orange_Side = ifelse(grepl("Orange Side", attributes), 1, 0),
         Buck_Teeth = ifelse(grepl("Buck Teeth", attributes), 1, 0),
         Welding_Goggles = ifelse(grepl("Welding Goggles", attributes), 1, 0),
         Pigtails = ifelse(grepl("Pigtails", attributes), 1, 0),
         Pink_With_Hat = ifelse(grepl("Pink With Hat", attributes), 1, 0),
         Top_Hat= ifelse(grepl("Top Hat", attributes), 1, 0),
         Spots = ifelse(grepl("Spots", attributes), 1, 0),
         Rosy_Cheeks = ifelse(grepl("Rosy Cheeks", attributes), 1, 0),
         Blonde_Short = ifelse(grepl("Blonde Short", attributes), 1, 0),
         Wild_White_Hair = ifelse(grepl("Wild White Hair", attributes), 1, 0),
         Cowboy_Hat = ifelse(grepl("Cowboy Hat", attributes), 1, 0),
         Wild_Blonde = ifelse(grepl("Wild Blonde", attributes), 1, 0),
         Straight_Hair_Blonde = ifelse(grepl("Straight Hair Blonde", attributes), 1, 0),
         Big_Beard = ifelse(grepl("Big Beard", attributes), 1, 0),
         Red_Mohawk = ifelse(grepl("Red Mohawk", attributes), 1, 0),
         Half_Shaved= ifelse(grepl("Half Shaved", attributes), 1, 0),
         Blonde_Bob= ifelse(grepl("Blonde Bob", attributes), 1, 0),
         Vampire_Hair= ifelse(grepl("Vampire Hair", attributes), 1, 0),
         Clown_Hair_Green = ifelse(grepl("Clown Hair Green", attributes), 1, 0),
         Straight_Hair_Dark = ifelse(grepl("Straight Hair Dark", attributes), 1, 0),
         Straight_Hair = ifelse(grepl("Straight Hair", attributes), 1, 0),
         Silver_Chain= ifelse(grepl("Silver Chain", attributes), 1, 0),
         Dark_Hair = ifelse(grepl("Dark Hair", attributes), 1, 0),
         Purple_Hair = ifelse(grepl("Purple Hair", attributes), 1, 0),
         Gold_Chain = ifelse(grepl("Gold Chain", attributes), 1, 0),
         Medical_Mask = ifelse(grepl("Medical Mask", attributes), 1, 0),
         Tassle_Hat = ifelse(grepl("Tassle Hat", attributes), 1, 0),
         Fedora = ifelse(grepl("Fedora", attributes), 1, 0),
         Police_Cap = ifelse(grepl("Police Cap", attributes), 1, 0),
         Clown_Nose = ifelse(grepl("Clown Nose", attributes), 1, 0),
         Cap_Forward = ifelse(grepl("Cap Forward", attributes), 1, 0),
         Hoodie = ifelse(grepl("Hoodie", attributes), 1, 0),
         Front_Beard_Dark = ifelse(grepl("Front Beard Dark", attributes), 1, 0),
         Frown = ifelse(grepl("Frown", attributes), 1, 0),
         Purple_Eye_Shadow = ifelse(grepl("Purple Eye Shadow", attributes), 1, 0),
         Handlebars = ifelse(grepl("Handlebars", attributes), 1, 0),
         Blue_Eye_Shadow = ifelse(grepl("Blue Eye Shadow", attributes), 1, 0),
         Green_Eye_Shadow = ifelse(grepl("Green Eye Shadow", attributes), 1, 0),
         Vape = ifelse(grepl("Vape", attributes), 1, 0),
         Front_Beard = ifelse(grepl("Front Beard", attributes), 1, 0),
         Chinstrap = ifelse(grepl("Chinstrap", attributes), 1, 0),
         D_Glasses = ifelse(grepl("3D Glasses", attributes), 1, 0),
         Luxurious_Beard = ifelse(grepl("Luxurious Beard", attributes), 1, 0),
         Mustache = ifelse(grepl("Mustache", attributes), 1, 0),
         Normal_Beard_Black = ifelse(grepl("Normal Beard Black", attributes), 1, 0),
         Normal_Beard = ifelse(grepl("Normal Beard", attributes), 1, 0),
         Eye_Mask = ifelse(grepl("Eye Mask", attributes), 1, 0),
         Goat = ifelse(grepl("Goat", attributes), 1, 0),
         Do_rag = ifelse(grepl("Do-rag", attributes), 1, 0),
         Shaved_Head = ifelse(grepl("Shaved Head", attributes), 1, 0),
         Muttonchops = ifelse(grepl("Muttonchops", attributes), 1, 0),
         Peak_Spike = ifelse(grepl("Peak Spike", attributes), 1, 0),
         Pipe = ifelse(grepl("Pipe", attributes), 1, 0),
         VR = ifelse(grepl("VR", attributes), 1, 0),
         Cap = ifelse(grepl("Cap", attributes), 1, 0),
         Small_Shades = ifelse(grepl("Small Shades", attributes), 1, 0),
         Clown_Eyes_Green = ifelse(grepl("Clown Eyes Green", attributes), 1, 0),
         Clown_Eyes_Blue = ifelse(grepl("Clown Eyes Blue", attributes), 1, 0),
         Headband = ifelse(grepl("Headband", attributes), 1, 0),
         Crazy_Hair = ifelse(grepl("Crazy Hair", attributes), 1, 0),
         Knitted_Cap = ifelse(grepl("Knitted Cap", attributes), 1, 0),
         Mohawk_Dark = ifelse(grepl("Mohawk Dark", attributes), 1, 0),
         Mohawk = ifelse(grepl("Mohawk", attributes), 1, 0),
         Mohawk_Thin = ifelse(grepl("Mohawk Thin", attributes), 1, 0),
         Frumpy_Hair = ifelse(grepl("Frumpy Hair", attributes), 1, 0),
         Wild_Hair = ifelse(grepl("Wild Hair", attributes), 1, 0),
         Messy_Hair = ifelse(grepl("Messy Hair", attributes), 1, 0),
         Eye_Patch = ifelse(grepl("Eye Patch", attributes), 1, 0),
         Stringy_Hair = ifelse(grepl("Stringy Hair", attributes), 1, 0),
         Classic_Shades = ifelse(grepl("Classic Shades", attributes), 1, 0),
         Shadow_Beard = ifelse(grepl("Shadow Beard", attributes), 1, 0),
         Regular_Shades = ifelse(grepl("Regular Shades", attributes), 1, 0),
         Horned_Rim_Glasses = ifelse(grepl("Horned Rim Glasses", attributes), 1, 0),
         Big_Shades = ifelse(grepl("Big Shades", attributes), 1, 0),
         Nerd_Glasses = ifelse(grepl("Nerd Glasses", attributes), 1, 0),
         Black_Lipstick = ifelse(grepl("Black Lipstick", attributes), 1, 0),
         Mole = ifelse(grepl("Mole", attributes), 1, 0),
         Purple_Lipstick = ifelse(grepl("Purple Lipstick", attributes), 1, 0),
         Hot_Lipstick = ifelse(grepl("Hot Lipstick", attributes), 1, 0),
         Cigarette = ifelse(grepl("Cigarette", attributes), 1, 0),
         Earring = ifelse(grepl("Earring", attributes), 1, 0))


